Feature / participant screen
vkluchenkov/judging-app pull request #5
Opened 2022-05-14 14:11 UTC by vkluchenkov

2022-05-14 16:43 UTC, ArtemAstakhov requested changes

2022-05-14 16:43 UTC, ArtemAstakhov commented on src/components/Scoring/index.tsx
> +  const ScoringList = () => criterias.map((criteria) => {
почему функция?
оберни в useMemo

2022-05-14 17:15 UTC, vkluchenkov commented on src/components/Scoring/index.tsx
> +  const ScoringList = () => criterias.map((criteria) => {
Поправил

2022-05-14 21:49 UTC, ArtemAstakhov requested changes

2022-05-14 21:49 UTC, ArtemAstakhov commented on src/ui-kit/ScoringSlider/index.tsx
> +      marks={[
[1, 2, 3, ...., 10].map((i) => ({value: i, label: i}))

2022-05-14 21:49 UTC, ArtemAstakhov commented on src/components/Scoring/index.tsx
> +    setSliders((state) => {
что тут происходит?

2022-05-14 22:01 UTC, vkluchenkov commented on src/components/Scoring/index.tsx
> +    setSliders((state) => {
Установка default value в стейт при маппинге. Иначе при сабмите с дефолтным значением в стейте пусто.

2022-05-14 22:04 UTC, vkluchenkov commented on src/ui-kit/ScoringSlider/index.tsx
> +      marks={[
Да, я примерно так и собирался. На время экспериментов написал тупо и забыл поправить.. запушил.

2022-05-15 08:32 UTC, ArtemAstakhov commented on src/components/Scoring/index.tsx
> +    setSliders((state) => {
почему не установишь его в useState?

2022-05-15 08:38 UTC, ArtemAstakhov commented on src/components/Scoring/index.tsx
> +    setSliders((state) => {
вообще есть сомнения что это работает, ведь ты внутри хука который подписан на slider меняешь sliders
возниникает циклическая зависимость

2022-05-15 09:50 UTC, ArtemAstakhov approved these changes

2022-05-15 09:54 UTC, merged